NEXMON_CHIP=CHIP_VER_WIL6210
NEXMON_CHIP_NUM=`$(NEXMON_ROOT)/buildtools/scripts/getdefine.sh $(NEXMON_CHIP)`
NEXMON_FW_VERSION=FW_VER_410_55
NEXMON_FW_VERSION_NUM=`$(NEXMON_ROOT)/buildtools/scripts/getdefine.sh $(NEXMON_FW_VERSION)`

NEXMON_ARCH=arc600

FW_FILE=wil6210.fw

FW_CODE_FILE=wil6210.fw_code
FW_CODE_START=0x8c0000
FW_CODE_SIZE=0x40000
FW_CODE_PARTITION=1

FW_DATA_FILE=wil6210.fw_data
FW_DATA_START=UNDEF
FW_DATA_SIZE=0x8000
FW_DATA_PARTITION=2

UC_CODE_FILE=wil6210.uc_code
UC_CODE_START=0x920000
UC_CODE_SIZE=0x20000
UC_CODE_PARTITION=3

UC_DATA_FILE=wil6210.uc_data
UC_DATA_START=UNDEF
UC_DATA_SIZE=0x4000
UC_DATA_PARTITION=4

FW_PATCH_START_OFFSET=0x35200
FW_PATCH_START=$$(($(FW_CODE_START) + $(FW_PATCH_START_OFFSET)))
FW_PATCH_SIZE=$$(($(FW_CODE_SIZE) - $(FW_PATCH_START_OFFSET)))

UC_PATCH_START_OFFSET=0x18700
UC_PATCH_STATIC_DATA=0x3000 
UC_PATCH_START=$$(($(UC_CODE_START) + $(UC_PATCH_START_OFFSET)))
UC_PATCH_SIZE=$$(($(UC_CODE_SIZE) - $(UC_PATCH_START_OFFSET) - $(UC_PATCH_STATIC_DATA)))


